name: CI - Request Deployment Approval
description: "Request Deployment Approval"

inputs:
  devOpsProj:
    required: true
    description: 'Azure Devops Project Name'
  devOpsOrg:
    required: true
    description: 'Azure Devops Org'
  devOpsBranch:
    description: ''
    default: 'main'
  devOpsPipelineName:
    description: ''
    default: 'Deploy_Request'
  environment:
    required: true
    description: ''
  clientId:
    required: true
    description: ''
  tenantId:
    required: true
    description: ''
  subscriptionId:
    required: true
    description: ''
  azdo_pat:
    required: true
    description: 'Azure DevOps Personal Access Token'

runs:
  using: composite
  steps:
  - uses: actions/checkout@v3
  
  - name: Azure Login
    uses: azure/login@v1
    with:
      client-id: ${{ inputs.clientId }}
      tenant-id: ${{ inputs.tenantId }}
      subscription-id: ${{ inputs.subscriptionId }}

  - name: "Deployment Approval Request"
    uses: ./.github/actions/az-devops-approval-request
    id: deployment_approval
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ inputs.azdo_pat }}
    with:
      project: ${{ inputs.devOpsProj }}
      org: ${{ inputs.devOpsOrg }}
      branch: ${{ inputs.devOpsBranch }}
      pipeline_name: ${{ inputs.devOpsPipelineName }}
      environment: ${{ inputs.environment }}
