name: 'Azure DevOps - Approval Request'
description: 'Creates a deployment approval for an Azure DevOps project.'
author: 'JERA'

inputs:
  project:
    description: 'Name or ID of the project.'
    required: true
  org:
    description: 'Azure DevOps organization URL.'
    required: true
  branch:
    description: 'Branch name for which the pipeline will be configured.'
    required: true
  pipeline_name:
    description: 'AZ DevOps pipeline name'
    required: true
  environment:
    description: 'Deployment environment name on AZ DevOps.'
    required: true
  duration:
    description: 'How long the script will wait for approval, in days. Defaults to 10 days.'
    default: '10'
    required: false
  poll_interval:
    description: 'The polling interval in seconds.'
    default: '10'
    required: false

runs:
  using: 'composite'
  steps:
  - shell: bash
    run: chmod +x .github/scripts/request_approval.sh

  - shell: bash
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ env.AZURE_DEVOPS_EXT_PAT }}
    run: |
      ./.github/scripts/request_approval.sh \
        -project "${{ inputs.project }}" \
        -org "${{ inputs.org }}" \
        -branch "${{ inputs.branch }}" \
        -name "${{ inputs.pipeline_name }}" \
        -environment "Development" \
        -duration "${{ inputs.duration }}" \
        -interval "${{ inputs.poll_interval }}"


